WIDTH, HEIGHT = 1280, 720

ROWS, COLS = 4, 4
GRID_WIDTH = 360  # Make it wide enough for 16 columns
CELL_SIZE = GRID_WIDTH // COLS
START_X = (WIDTH - GRID_WIDTH) // 2
START_Y = (HEIGHT - (ROWS * CELL_SIZE)) // 2 + 50
FPS = 60

ALPHABET = (
"EEEEEEEE"
"AAAAAA"
"IIIIII"
"OOOOOO"
"UUUU"
"NNNNNN"
"RRRRRR"
"TTTTTT"
"LLLL"
"SSSS"
"BCDFGHJKMPVWY"
"XZQ"
)
